language: python
python: "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test
  - pep8
  - flake8
after_success:
  coveralls
notifications:
  slack: corporate:wLpIB1JP65wXQlMTOb6OPtub
  flowdock: 254bd409c0975bbdea62d406936a3072
